Fix duplicate private_cluster_config
GoogleCloudPlatform/ai-on-gke pull request #669
Opened 2024-05-14 17:04 UTC by hubatish

After lots of merges & attempted squashes from me being new to making pull requests, the private_cluster_config was duplicated & a couple other changes seemed incorrect. READMEs haven't been updated so these should be only changes necessary. Have tested with just terraform init & terraform plan.

2024-05-15 17:26 UTC, hubatish commented
Ran terraform destroy & apply on my existing setup successfully. From blank, terraform apply with private_cluster_config = null in tfvars creates a cluster with "Private cluster" disabled & terraform plan with private_cluster_config = {} from there tries to swap it. Oddly, an already spun up private cluster didn't offer to swap with terraform plan private_cluster_config = null

2024-05-15 20:30 UTC, annapendleton requested changes

2024-05-15 20:30 UTC, annapendleton commented on benchmarks/infra/stage-1/README.md
> +## Inputs
same comment as below

2024-05-15 20:32 UTC, annapendleton commented
> Ran terraform destroy & apply on my existing setup successfully. From blank, terraform apply with private_cluster_config = null in tfvars creates a cluster with "Private cluster" disabled & terraform plan with private_cluster_config = {} from there tries to swap it. Oddly, an already spun up private cluster didn't offer to swap with terraform plan private_cluster_config = null

oh interesting - I wonder if we should document this behavior as well? IMO it's likely an implementation detail in the modules we rely on for not changing private back to public

2024-05-15 21:49 UTC, hubatish commented on benchmarks/infra/stage-1/modules/gke-infra/README.md
> +<!-- BEGIN_TF_DOCS -->
Ah, manual modifications on top of running `terraform fmt` is not ideal.. have made those changes though.

2024-05-15 21:50 UTC, hubatish commented on benchmarks/infra/stage-1/README.md
> +## Inputs
Done

2024-05-15 21:50 UTC, hubatish commented
> > Ran terraform destroy & apply on my existing setup successfully. From blank, terraform apply with private_cluster_config = null in tfvars creates a cluster with "Private cluster" disabled & terraform plan with private_cluster_config = {} from there tries to swap it. Oddly, an already spun up private cluster didn't offer to swap with terraform plan private_cluster_config = null
> 
> oh interesting - I wonder if we should document this behavior as well? IMO it's likely an implementation detail in the modules we rely on for not changing private back to public

Sure, added a note in the variables.tf description.

2024-05-16 00:23 UTC, annapendleton commented on benchmarks/infra/stage-1/modules/gke-infra/README.md
> +<!-- BEGIN_TF_DOCS -->
+1, ty for doing it this time! And we can see if we can find a better long-term solution as well (eg. maybe it makes more sense to slowly shift all our docs to abide by the automated formatted way)

2024-05-16 00:23 UTC, annapendleton approved these changes

2024-05-16 17:55 UTC, merged