Update HuggingFace DLC for TGI URI to 2.3 (latest)
GoogleCloudPlatform/ai-on-gke pull request #852
Opened 2024-10-18 06:52 UTC by alvarobartt

## Description

As a follow up PR of #816 recently merged, this PR contains the update to the latest version as of today of the Hugging Face DLC for TGI on Google Cloud, which is TGI 2.3.1 labelled as TGI 2.3.

Thanks in advance 🤗 

cc @annapendleton

2024-10-28 18:12 UTC, annapendleton approved these changes

2024-10-28 18:12 UTC, annapendleton commented
/gcbrun

2025-01-07 18:42 UTC, raushan2016 commented on modules/inference-service/main.tf
> +            mount_path = "/tmp"
Since this `mounth_path` is tightly coupled with the container image used. Can we add some comment or details around why it needs to be exactly `/tmp`. This would avoid someone changing it later resulting into things not working ?

2025-01-07 18:47 UTC, raushan2016 commented on tutorials-and-examples/genAI-LLM/deploying-mixtral-8x7b-instruct-L4-gpus/README.md
#L147 also needs to updated from `/data/` to `/tmp`

2025-01-07 18:50 UTC, raushan2016 commented on tutorials-and-examples/genAI-LLM/deploying-mistral-7b-instruct-L4gpus/README.md
#L118 simiar change needed

2025-01-07 18:53 UTC, raushan2016 requested changes

2025-01-07 18:53 UTC, raushan2016 commented on tutorials-and-examples/genAI-LLM/serving-llama2-70b-on-l4-gpus/README.md
#L100 similar change needed

2025-01-08 18:27 UTC, annapendleton commented
/gcbrun

2025-01-09 00:00 UTC, raushan2016 commented
Still has issues check 
https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/1584#discussion_r1907879386

2025-01-10 17:29 UTC, raushan2016 commented
@alvarobartt should we revert to the old image to have the main branch sample in working state while we investigate. Once we have the fix we can update the image with additional changes ?

cc @annapendleton

2025-01-16 08:17 UTC, alvarobartt commented
Is this still the case @raushan2016? Should we instead update the image URI to point to the actual latest being `us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-text-generation-inference-cu124.2-4.ubuntu2204.py311` as per https://cloud.google.com/deep-learning-containers/docs/choosing-container#hugging-face, and make sure that it works just fine with that image URI? cc @annapendleton Thank you both in advance! 🤗

2025-02-27 20:27 UTC, annapendleton commented
@alvarobartt following up, we don't have any automated tests that will validate this. Will you please manually validate this change on a cluster? I can sign off after confirmation.

2025-03-18 17:24 UTC, roberthbailey commented
@alvarobartt - Since this PR needs a rebase and manual testing before it can be merged and hasn't had any updates this calendar year, I'm going to close it. If you would like to resume making this change, please feel free to re-open the pull request and we can resume reviewing it. 

Thanks!

2025-03-18 17:24 UTC, closed without merging