Adding GMP and Cloud Monitoring for gke-batch-refarch
GoogleCloudPlatform/ai-on-gke pull request #856
Opened 2024-10-24 18:26 UTC by JamesDuncanNz

Adding support for GMP Managed Collection and Cloud Monitoring Dashboard for gke-batch-refarch.

2024-10-24 18:54 UTC, alculquicondor commented on best-practices/gke-batch-refarch/02_platform/monitoring/gmp/README.md
> +Kueue metrics are automatically collected by Google Managed Prometheus using managed collection. This means Prometheus-based collectors run as a Daemonset, ensuring scalability by only scraping targe
```suggestion
You can configure Google Managed Prometheus to automatically collect Kueue metrics. The collected metrics are then exported and made available in Google Cloud's Monitoring service.
```

The rest seems to be documentation for GMP itself, which is not relevant here.

2024-10-24 18:54 UTC, alculquicondor commented on best-practices/gke-batch-refarch/02_platform/monitoring/gmp/README.md
> +The following command will configure Managed Collection for Kueue and Create the Dashboard in Cloud Monitoring.
```suggestion
Run the following command to configure Managed Collection for Kueue and Create the Dashboard in Cloud Monitoring. 
```

Also, shouldn't this section be before "Viewing the Dashaboard"?

2024-10-24 18:54 UTC, alculquicondor commented on best-practices/gke-batch-refarch/02_platform/monitoring/gmp/kueue-dashboard.json
is this the same dashboard as the one outside of the gmp folder?

Should we remove the other mechanism? The Ref architecture is supposed to be opinionated.

2024-10-24 20:47 UTC, JamesDuncanNz commented on best-practices/gke-batch-refarch/02_platform/monitoring/gmp/kueue-dashboard.json
The dashboard is slightly different, but was heavily inspired from the dashboard in the parent folder. I had to use some additional metrics that weren't available in Cloud Monitoring and added a graph or two.

2024-10-25 07:50 UTC, laurentgrangeau requested changes
Hey, some minor changes and it should be good to go

2024-10-25 07:50 UTC, laurentgrangeau commented on best-practices/gke-batch-refarch/02_platform/monitoring/gmp/gmp-kueue-monitoring.yaml
> +  kind: ServiceAccount
I suggest adding a line break

2024-10-25 07:50 UTC, laurentgrangeau commented on best-practices/gke-batch-refarch/02_platform/monitoring/gmp/install-gmp.sh
> +[[ ! "${PROJECT_ID}" ]] && echo -e "Please export PROJECT_ID variable (\e[95mexport PROJECT_ID=<YOUR POROJECT ID>\e[0m)\nExiting." && exit 0
I suggest adding a copyright header for this code

2024-10-25 07:50 UTC, laurentgrangeau commented on best-practices/gke-batch-refarch/02_platform/monitoring/gmp/install-gmp.sh
> +gcloud monitoring dashboards create --project=$PROJECT_ID --config-from-file=kueue-dashboard.json
I suggest adding a line break

2024-10-25 15:06 UTC, alculquicondor approved these changes

2024-10-28 13:26 UTC, JamesDuncanNz commented on best-practices/gke-batch-refarch/02_platform/monitoring/gmp/kueue-dashboard.json
@laurentgrangeau Are you ok with this?

2024-10-28 13:45 UTC, laurentgrangeau commented on best-practices/gke-batch-refarch/02_platform/monitoring/gmp/kueue-dashboard.json
Yes, I'm OK with this

2024-10-28 16:19 UTC, merged